// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TurboNative__SignOutController from "./turbo_native/sign_out_controller.js"
application.register("turbo-native--sign-out", TurboNative__SignOutController)
